### Grid Search CV

In [51]:
import pandas as pd
import seaborn as sns

In [52]:
df = sns.load_dataset('iris')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [53]:
df.drop_duplicates()

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[149 rows x 5 columns]

In [54]:
from sklearn.model_selection import train_test_split
X = df.drop('species',axis=1)
y = df['species']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [55]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=30 , weights='distance' , algorithm='auto' ,metric='minkowski')
knn_model.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=30, weights='distance')

In [56]:
y_predict = knn_model.predict(X_test)

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_predict)

0.9666666666666667

First, we choose a model and define its hyperparameters with different values. Then GridSearchCV creates all possible combinations of these hyperparameters. For each combination, it applies cross validation on the dataset by splitting it into folds and calculates the average accuracy. After testing all combinations, it selects the best hyperparameters based on the highest score and returns the best model.

In [58]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(
    estimator=knn_model,
    param_grid={
        'n_neighbors': [1,2,3,4,5,6,7,8,9],
        'weights': ['uniform', 'distance'],
        'algorithm': ['ball_tree', 'kd_tree', 'brute'],
        'metric': ['euclidean', 'manhattan', 'minkowski']
    },
    cv=5,
    scoring='accuracy'
)

grid.fit(X , y)

GridSearchCV(cv=5,
             estimator=KNeighborsClassifier(n_neighbors=30, weights='distance'),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [59]:
print(grid.best_params_)   
print(grid.best_score_)

{'algorithm': 'ball_tree', 'metric': 'euclidean', 'n_neighbors': 6, 'weights': 'uniform'}
0.9800000000000001

In [60]:
print(grid.cv_results_)
dataF = pd.DataFrame(data=grid.cv_results_)
dataF

{'mean_fit_time': array([0.00560083, 0.00351825, 0.00300474, 0.00319982, 0.00326519,
       0.00319963, 0.00339837, 0.00319614, 0.0032001 , 0.00340009,
       0.00299959, 0.00339999, 0.0032002 , 0.00319996, 0.00320005,
       0.00299988, 0.00339999, 0.00300045, 0.00359674, 0.00299997,
       0.00319724, 0.00299997, 0.00319977, 0.00319977, 0.00339975,
       0.00340018, 0.00339952, 0.0032002 , 0.00312095, 0.00312862,
       0.00300064, 0.00299716, 0.00359988, 0.00305972, 0.00299997,
       0.00320005, 0.00280013, 0.00319991, 0.00279994, 0.00315604,
       0.0032001 , 0.00319986, 0.00320005, 0.00299997, 0.0027987 ,
       0.00280042, 0.00299983, 0.00339999, 0.00280004, 0.00320001,
       0.00320683, 0.00299683, 0.00524278, 0.00469794, 0.0045517 ,
       0.00339961, 0.0030004 , 0.00300026, 0.00319777, 0.00300002,
       0.00300145, 0.00373235, 0.00350962, 0.00354848, 0.00312328,
       0.00349817, 0.00329099, 0.00333905, 0.00326524, 0.00321746,
       0.0033453 , 0.00349669, 0.00307612, 0.00319996, 0.00341978,
       0.00350089, 0.00354543, 0.00342641, 0.00320406, 0.00356188,
       0.00314412, 0.00314169, 0.00300565, 0.0030025 , 0.00320363,
       0.00300031, 0.00299931, 0.00319967, 0.00300064, 0.0031023 ,
       0.00299497, 0.00299983, 0.00324497, 0.00300131, 0.00300145,
       0.00330157, 0.0030931 , 0.00306101, 0.003197  , 0.00326757,
       0.00307975, 0.00300064, 0.00299888, 0.00293856, 0.00303435,
       0.00339785, 0.00321684, 0.00352793, 0.00300641, 0.00400071,
       0.0032002 , 0.00299945, 0.00300403, 0.00366735, 0.00340075,
       0.00340309, 0.0025001 , 0.00360007, 0.00300136, 0.00339971,
       0.00302525, 0.00360022, 0.00300035, 0.00340056, 0.00281692,
       0.00320387, 0.0024992 , 0.0029994 , 0.00320005, 0.00340028,
       0.00303192, 0.00339937, 0.00287938, 0.00321412, 0.00300045,
       0.00320144, 0.00322208, 0.00320106, 0.00280013, 0.00360031,
       0.00302987, 0.00320106, 0.00300303, 0.0038013 , 0.00348659,
       0.00379972, 0.00449777, 0.00380187, 0.00299997, 0.0036725 ,
       0.00340934, 0.00360026, 0.00381355, 0.00339932, 0.00359869,
       0.0035955 , 0.00347385, 0.00320697, 0.00371876, 0.00399952,
       0.00279994, 0.00321722]), 'std_fit_time': array([1.01867378e-03, 1.03657250e-03, 9.38218763e-06, 3.99947405e-04,
       3.94815276e-04, 3.99684991e-04, 4.87887197e-04, 4.01969556e-04,
       3.99685105e-04, 7.99715581e-04, 3.50402318e-07, 4.89570515e-04,
       3.99994946e-04, 3.99875726e-04, 3.99708872e-04, 1.16800773e-07,
       4.89862534e-04, 5.30983387e-07, 4.87250944e-04, 3.50402318e-07,
       4.01269147e-04, 4.86280395e-07, 3.99732974e-04, 3.99971065e-04,
       4.89959789e-04, 4.89804116e-04, 4.89862557e-04, 3.99994889e-04,
       1.48249386e-04, 6.82712933e-04, 4.42200589e-07, 5.72403238e-06,
       8.00013562e-04, 1.19280851e-04, 9.53674316e-08, 3.99947177e-04,
       4.00018763e-04, 3.99899493e-04, 4.00042545e-04, 4.30370106e-04,
       4.00042772e-04, 3.99684906e-04, 3.99947433e-04, 6.32259018e-04,
       3.99315309e-04, 4.00042630e-04, 4.10190833e-07, 4.89668013e-04,
       4.00090313e-04, 3.99851810e-04, 3.96889433e-04, 6.63917621e-06,
       1.12313109e-03, 7.33717496e-04, 1.10131549e-03, 4.89299265e-04,
       3.23406696e-07, 6.32485172e-04, 4.01486739e-04, 3.98950589e-07,
       2.65063135e-06, 9.35623823e-04, 5.59673618e-04, 6.45121512e-04,
       1.59949195e-04, 7.64523554e-04, 5.25117504e-04, 4.21095756e-04,
       3.89050868e-04, 5.20215747e-04, 5.09673735e-04, 4.98396653e-04,
       6.58112870e-04, 3.90176404e-04, 3.79702845e-04, 7.06557510e-04,
       5.86437178e-04, 7.78145730e-04, 4.07481232e-04, 1.00652585e-03,
       1.97939843e-04, 4.91121333e-04, 6.31601526e-04, 1.48652407e-05,
       4.00462171e-04, 4.10190833e-07, 2.41733396e-06, 4.01220957e-04,
       3.23406696e-07, 2.05636930e-04, 1.03588963e-05, 1.72849359e-06,
       3.88488354e-04, 1.25798282e-06, 1.63798943e-06, 7.86590053e-04,
       7.06545220e-04, 6.56162642e-04, 3.95519778e-04, 3.79101117e-04,
       1.04596880e-04, 1.28480850e-06, 2.33309361e-06, 5.05180815e-04,
       6.81882138e-05, 4.86972842e-04, 4.00486829e-04, 4.95212375e-04,
       1.06350722e-05, 6.33391027e-04, 3.99518109e-04, 6.33541460e-04,
       6.14250663e-06, 1.05409561e-03, 8.00991371e-04, 4.93974128e-04,
       4.47181217e-04, 4.89648645e-04, 2.37750070e-06, 4.89609711e-04,
       5.08075306e-05, 4.89669058e-04, 6.32485201e-04, 4.91051735e-04,
       4.09784876e-04, 4.07815854e-04, 6.24678418e-04, 5.35248383e-07,
       3.99352387e-04, 4.88754445e-04, 6.35457883e-04, 4.90370463e-04,
       4.64536340e-04, 7.25520813e-04, 1.36044909e-06, 7.48980822e-04,
       3.90278750e-04, 7.49400901e-04, 4.00138707e-04, 7.99989736e-04,
       6.36807768e-05, 7.49401174e-04, 6.32507381e-04, 7.49017857e-04,
       7.70949772e-04, 3.99494285e-04, 1.00126923e-03, 4.00931346e-04,
       6.32711385e-04, 7.60561599e-04, 4.92886838e-04, 4.90001483e-04,
       7.47839107e-04, 4.89823956e-04, 8.00194286e-04, 4.86603491e-04,
       5.92540608e-04, 3.98936626e-04, 8.79022182e-04, 6.31583397e-04,
       3.99923566e-04, 9.76240896e-04]), 'mean_score_time': array([0.00960064, 0.0041997 , 0.07948737, 0.00420017, 0.00533476,
       0.00400023, 0.0050015 , 0.00400372, 0.00499997, 0.00440006,
       0.00480027, 0.0039999 , 0.00499978, 0.00420003, 0.00480747,
       0.00420294, 0.00679994, 0.00459976, 0.00520325, 0.00440006,
       0.00480003, 0.004     , 0.00460014, 0.00400033, 0.00500021,
       0.00439978, 0.00520034, 0.0039999 , 0.00507917, 0.004     ,
       0.00479937, 0.00419989, 0.00520024, 0.00414028, 0.00499992,
       0.00399981, 0.00500002, 0.0046001 , 0.0052    , 0.00399981,
       0.00539999, 0.00380011, 0.00500016, 0.00420017, 0.00459967,
       0.00459991, 0.0052    , 0.00444546, 0.00519991, 0.00444417,
       0.00479312, 0.00471072, 0.00839853, 0.00585747, 0.00647526,
       0.0039999 , 0.00479956, 0.00439959, 0.00480208, 0.004     ,
       0.00499845, 0.00400505, 0.00500779, 0.00465646, 0.00500765,
       0.00422153, 0.00483255, 0.00400062, 0.0046001 , 0.0046597 ,
       0.00479813, 0.004217  , 0.00499811, 0.00399995, 0.00479617,
       0.00419841, 0.00497079, 0.00456061, 0.0052464 , 0.0042459 ,
       0.0046875 , 0.00411596, 0.00548539, 0.00437975, 0.00510707,
       0.00426002, 0.00557752, 0.00401635, 0.00522346, 0.00454311,
       0.00506549, 0.00440664, 0.00502467, 0.00447116, 0.00506349,
       0.0040019 , 0.00479512, 0.00421286, 0.00500627, 0.00424271,
       0.00469322, 0.00450482, 0.00484891, 0.00430923, 0.00499768,
       0.00422821, 0.00524378, 0.00450878, 0.00779805, 0.00890298,
       0.00738921, 0.00834274, 0.00762234, 0.00944014, 0.00805902,
       0.0076283 , 0.00791922, 0.00804973, 0.00741558, 0.00863376,
       0.0077827 , 0.00835099, 0.00763607, 0.00838799, 0.00767646,
       0.00871506, 0.00627069, 0.00811801, 0.00616136, 0.00828128,
       0.00621839, 0.00811076, 0.00634041, 0.00779691, 0.00584574,
       0.00804315, 0.00608344, 0.00797381, 0.00638075, 0.00820022,
       0.00616927, 0.00812664, 0.0063354 , 0.00893674, 0.00850697,
       0.00960445, 0.01355786, 0.01001201, 0.00799947, 0.00909944,
       0.0081131 , 0.0099545 , 0.00871997, 0.00965371, 0.00860648,
       0.00950346, 0.00826416, 0.0085176 , 0.010145  , 0.0091445 ,
       0.00800657, 0.00825772]), 'std_score_time': array([1.95950360e-03, 4.00091422e-04, 1.48974991e-01, 4.00090768e-04,
       4.28667551e-04, 3.81469727e-07, 3.74066518e-06, 7.53402710e-06,
       1.16800773e-07, 8.00228190e-04, 3.99804297e-04, 2.78041453e-07,
       6.32334304e-04, 3.99684934e-04, 4.04142292e-04, 3.98742214e-04,
       2.22717558e-03, 4.89551398e-04, 7.47212286e-04, 4.89648459e-04,
       3.99923453e-04, 2.78041453e-07, 4.89959835e-04, 2.43140197e-07,
       6.32560582e-04, 4.89687269e-04, 3.99851952e-04, 9.53674316e-08,
       7.08788893e-04, 6.32334318e-04, 4.00543241e-04, 4.00114102e-04,
       4.00137969e-04, 4.45018215e-04, 6.32485125e-04, 3.23406696e-07,
       6.32635882e-04, 4.89726234e-04, 3.99899522e-04, 3.23406696e-07,
       7.99632234e-04, 4.00042573e-04, 3.16297988e-07, 3.99732661e-04,
       4.89765214e-04, 7.99822898e-04, 4.00137997e-04, 4.60172603e-04,
       3.99828028e-04, 4.60593161e-04, 7.46641535e-04, 8.76882420e-04,
       7.98765536e-04, 4.82385943e-04, 5.82312874e-04, 7.44843452e-07,
       3.99804154e-04, 4.89843011e-04, 4.01336435e-04, 5.09122765e-07,
       2.55007590e-06, 1.11630828e-05, 1.20531380e-05, 7.97943931e-04,
       2.51635422e-05, 3.91399419e-04, 8.07059468e-04, 2.06971497e-06,
       4.90213145e-04, 5.41288047e-04, 3.99572735e-04, 3.93312059e-04,
       6.31356646e-04, 5.00111031e-07, 4.06933110e-04, 4.08415371e-04,
       4.89209990e-04, 6.95463401e-04, 7.90234746e-04, 7.13106193e-04,
       5.76059497e-04, 1.88151242e-04, 5.99078868e-04, 5.35144594e-04,
       7.70173993e-04, 4.99206043e-04, 5.36481165e-04, 3.38931612e-05,
       2.62196334e-04, 6.77602370e-04, 6.42187910e-04, 6.32833971e-04,
       6.32534672e-04, 3.15206696e-04, 1.01790762e-04, 1.46517092e-05,
       3.97532261e-04, 4.14428965e-04, 1.23586404e-05, 4.85873372e-04,
       5.83967215e-04, 4.45963277e-04, 7.87943248e-04, 4.02029476e-04,
       5.51794909e-04, 4.60938274e-04, 3.75244395e-04, 5.92790147e-04,
       4.55603110e-04, 5.73135600e-04, 4.33465949e-04, 5.57337849e-04,
       3.56880953e-04, 9.00104102e-04, 1.30976362e-03, 8.19628685e-04,
       9.79152201e-04, 9.40279096e-04, 5.81642545e-04, 7.50138639e-04,
       4.31231105e-04, 5.93784094e-04, 4.48781771e-04, 3.44369584e-04,
       4.13810391e-04, 1.12428931e-03, 5.41663199e-04, 6.59041182e-04,
       2.12811339e-04, 2.52266569e-04, 5.67729566e-04, 3.73017521e-04,
       5.50434957e-04, 4.38830897e-04, 7.89993253e-04, 3.46760578e-04,
       3.02600027e-04, 6.21925904e-04, 5.20560581e-04, 4.34309069e-04,
       6.22942140e-04, 1.64100001e-04, 1.04527552e-03, 8.87904561e-04,
       8.24885745e-04, 9.47095615e-04, 4.60479852e-03, 2.65943681e-03,
       6.32485107e-04, 2.02928438e-04, 6.18377631e-04, 8.63903639e-04,
       9.10748205e-04, 5.88697632e-04, 4.92966039e-04, 4.74479344e-04,
       3.78993839e-04, 4.99587040e-04, 1.95045479e-03, 9.11527422e-04,
       4.18247215e-04, 7.46922352e-04]), 'param_algorithm': masked_array(data=['ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                   'ball_tree', 'ball_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                   'kd_tree', 'kd_tree', 'brute', 'brute', 'brute',
                   'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                   'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                   'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                   'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                   'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                   'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                   'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                   'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                   'brute', 'brute', 'brute'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_metric': masked_array(data=['euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski', 'minkowski', 'minkowski',
                   'minkowski', 'minkowski'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_n_neighbors': masked_array(data=[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                   1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                   1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                   1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                   1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                   1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                   1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                   1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                   1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005601,0.001019,0.009601,0.001960,ball_tree,euclidean,1,uniform,"{'algorithm': 'ball_tree', 'metric': 'euclidea...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,107
1,0.003518,0.001037,0.004200,0.000400,ball_tree,euclidean,1,distance,"{'algorithm': 'ball_tree', 'metric': 'euclidea...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,107
2,0.003005,0.000009,0.079487,0.148975,ball_tree,euclidean,2,uniform,"{'algorithm': 'ball_tree', 'metric': 'euclidea...",0.966667,0.933333,0.933333,0.900000,1.0,0.946667,0.033993,154
3,0.003200,0.000400,0.004200,0.000400,ball_tree,euclidean,2,distance,"{'algorithm': 'ball_tree', 'metric': 'euclidea...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,107
4,0.003265,0.000395,0.005335,0.000429,ball_tree,euclidean,3,uniform,"{'algorithm': 'ball_tree', 'metric': 'euclidea...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,0.003207,0.000399,0.008518,0.000500,brute,minkowski,7,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
158,0.003719,0.000879,0.010145,0.001950,brute,minkowski,8,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.966667,1.000000,0.933333,0.933333,1.0,0.966667,0.029814,57
159,0.004000,0.000632,0.009144,0.000912,brute,minkowski,8,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
160,0.002800,0.000400,0.008007,0.000418,brute,minkowski,9,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
161,0.003217,0.000976,0.008258,0.000747,brute,minkowski,9,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,31

In [65]:
from sklearn.model_selection import RandomizedSearchCV

grid_r = RandomizedSearchCV(
    estimator=knn_model,
    param_distributions={
        'n_neighbors': [1,2,3,4,5,6,7,8,9],
        'weights': ['uniform', 'distance'],
        'algorithm': ['ball_tree', 'kd_tree', 'brute'],
        'metric': ['euclidean', 'manhattan', 'minkowski']
    },
    n_iter=5,
    cv=5,
    scoring='accuracy'
)

grid_r.fit(X , y)

RandomizedSearchCV(cv=5,
                   estimator=KNeighborsClassifier(n_neighbors=30,
                                                  weights='distance'),
                   n_iter=5,
                   param_distributions={'algorithm': ['ball_tree', 'kd_tree',
                                                      'brute'],
                                        'metric': ['euclidean', 'manhattan',
                                                   'minkowski'],
                                        'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8,
                                                        9],
                                        'weights': ['uniform', 'distance']},
                   scoring='accuracy')

In [67]:
print(grid_r.best_score_)
print(grid_r.best_params_)

0.9733333333333334
{'weights': 'uniform', 'n_neighbors': 4, 'metric': 'minkowski', 'algorithm': 'ball_tree'}