### FIFA 2026 Data-Set Tunning

In [1]:
%pip install numpy 
%pip install pandas
%pip install seaborn 
%pip install matplotlib

Requirement already satisfied: numpy in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=9 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd 
import matplotlib.pyplot as mlt 
import seaborn as sns
import numpy as np

In [5]:
df = pd.read_csv("FIFA.csv")

In [ ]:
df.head() # here output feature is tournament_rating

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

In [7]:
df.isnull().sum()

player_id                   0
player_name                 0
age                         0
nationality                 0
team                        0
                           ..
total_goals_tournament      0
total_assists_tournament    0
total_minutes_tournament    0
player_of_match_awards      0
tournament_rating           0
Length: 75, dtype: int64

In [8]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
54595    False
54596    False
54597    False
54598    False
54599    False
Length: 54600, dtype: bool

In [13]:
%pip install sheryanalysis

Requirement already satisfied: sheryanalysis in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (0.1.0)
Requirement already satisfied: pandas>=1.0.0 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from sheryanalysis) (3.0.5)
Requirement already satisfied: numpy>=1.18.0 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from sheryanalysis) (2.4.6)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from sheryanalysis) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from pandas>=1.0.0->sheryanalysis) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from pandas>=1.0.0->sheryanalysis) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->sheryanalysis) (1.17.0)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from scikit-learn>=0.22.0->sheryanalysis) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from scikit-learn>=0.22.0->sheryanalysis) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from scikit-learn>=0.22.0->sheryanalysis) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages (from scikit-learn>=0.22.0->sheryanalysis) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [14]:
import sheryanalysis as sh 
sh.analyze(df)

🔍 Basic Analysis Report

c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)
c:\Users\zulka\anaconda3\envs\ml-learning\Lib\site-packages\sheryanalysis\utils.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample)

------------------------------------------------------------
📏 Shape: (54600, 75)
🧱 Columns: ['player_id', 'player_name', 'age', 'nationality', 'team', 'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot', 'club_name', 'market_value_eur', 'match_id', 'match_date', 'stadium', 'city', 'opponent_team', 'tournament_stage', 'match_result', 'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists', 'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa', 'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy', 'dribbles_attempted', 'successful_dribbles', 'crosses', 'successful_crosses', 'tackles', 'interceptions', 'clearances', 'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries', 'defensive_actions', 'fouls_committed', 'fouls_suffered', 'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage', 'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves', 'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh', 'accelerations', 'decelerations', 'stamina_score', 'player_rating', 'performance_score', 'offensive_contribution', 'defensive_contribution', 'possession_impact', 'pressure_resistance', 'creativity_score', 'consistency_score', 'clutch_performance_score', 'total_goals_tournament', 'total_assists_tournament', 'total_minutes_tournament', 'player_of_match_awards', 'tournament_rating']

✅ No null values found

🔠 Categorical Columns: ['player_id', 'player_name', 'age', 'nationality', 'team', 'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot', 'club_name', 'market_value_eur', 'stadium', 'city', 'opponent_team', 'tournament_stage', 'match_result', 'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists', 'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa', 'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy', 'dribbles_attempted', 'successful_dribbles', 'crosses', 'successful_crosses', 'tackles', 'interceptions', 'clearances', 'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries', 'defensive_actions', 'fouls_committed', 'fouls_suffered', 'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage', 'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves', 'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh', 'accelerations', 'decelerations', 'stamina_score', 'player_rating', 'performance_score', 'offensive_contribution', 'defensive_contribution', 'possession_impact', 'pressure_resistance', 'creativity_score', 'consistency_score', 'clutch_performance_score', 'total_goals_tournament', 'total_assists_tournament', 'total_minutes_tournament', 'player_of_match_awards', 'tournament_rating']

📅 Datetime Columns: ['match_id', 'match_date']

{'shape': (54600, 75),
 'columns': ['player_id',
  'player_name',
  'age',
  'nationality',
  'team',
  'jersey_number',
  'position',
  'height_cm',
  'weight_kg',
  'preferred_foot',
  'club_name',
  'market_value_eur',
  'match_id',
  'match_date',
  'stadium',
  'city',
  'opponent_team',
  'tournament_stage',
  'match_result',
  'goals_team',
  'goals_opponent',
  'minutes_played',
  'goals',
  'assists',
  'shots',
  'shots_on_target',
  'expected_goals_xg',
  'expected_assists_xa',
  'key_passes',
  'successful_passes',
  'total_passes',
  'pass_accuracy',
  'dribbles_attempted',
  'successful_dribbles',
  'crosses',
  'successful_crosses',
  'tackles',
  'interceptions',
  'clearances',
  'blocks',
  'aerial_duels_won',
  'aerial_duels_lost',
  'recoveries',
  'defensive_actions',
  'fouls_committed',
  'fouls_suffered',
  'yellow_cards',
  'red_cards',
  'offsides',
  'saves',
  'save_percentage',
  'punches',
  'clean_sheet',
  'goals_conceded',
  'penalty_saves',
  'distance_covered_km',
  'sprint_distance_km',
  'top_speed_kmh',
  'accelerations',
  'decelerations',
  'stamina_score',
  'player_rating',
  'performance_score',
  'offensive_contribution',
  'defensive_contribution',
  'possession_impact',
  'pressure_resistance',
  'creativity_score',
  'consistency_score',
  'clutch_performance_score',
  'total_goals_tournament',
  'total_assists_tournament',
  'total_minutes_tournament',
  'player_of_match_awards',
  'tournament_rating'],
 'dtypes': {'player_id': <StringDtype(storage='python', na_value=nan)>,
  'player_name': <StringDtype(storage='python', na_value=nan)>,
  'age': dtype('int64'),
  'nationality': <StringDtype(storage='python', na_value=nan)>,
  'team': <StringDtype(storage='python', na_value=nan)>,
  'jersey_number': dtype('int64'),
  'position': <StringDtype(storage='python', na_value=nan)>,
  'height_cm': dtype('int64'),
  'weight_kg': dtype('int64'),
  'preferred_foot': <StringDtype(storage='python', na_value=nan)>,
  'club_name': <StringDtype(storage='python', na_value=nan)>,
  'market_value_eur': dtype('int64'),
  'match_id': <StringDtype(storage='python', na_value=nan)>,
  'match_date': <StringDtype(storage='python', na_value=nan)>,
  'stadium': <StringDtype(storage='python', na_value=nan)>,
  'city': <StringDtype(storage='python', na_value=nan)>,
  'opponent_team': <StringDtype(storage='python', na_value=nan)>,
  'tournament_stage': <StringDtype(storage='python', na_value=nan)>,
  'match_result': <StringDtype(storage='python', na_value=nan)>,
  'goals_team': dtype('int64'),
  'goals_opponent': dtype('int64'),
  'minutes_played': dtype('int64'),
  'goals': dtype('int64'),
  'assists': dtype('int64'),
  'shots': dtype('int64'),
  'shots_on_target': dtype('int64'),
  'expected_goals_xg': dtype('float64'),
  'expected_assists_xa': dtype('float64'),
  'key_passes': dtype('int64'),
  'successful_passes': dtype('int64'),
  'total_passes': dtype('int64'),
  'pass_accuracy': dtype('float64'),
  'dribbles_attempted': dtype('int64'),
  'successful_dribbles': dtype('int64'),
  'crosses': dtype('int64'),
  'successful_crosses': dtype('int64'),
  'tackles': dtype('int64'),
  'interceptions': dtype('int64'),
  'clearances': dtype('int64'),
  'blocks': dtype('int64'),
  'aerial_duels_won': dtype('int64'),
  'aerial_duels_lost': dtype('int64'),
  'recoveries': dtype('int64'),
  'defensive_actions': dtype('int64'),
  'fouls_committed': dtype('int64'),
  'fouls_suffered': dtype('int64'),
  'yellow_cards': dtype('int64'),
  'red_cards': dtype('int64'),
  'offsides': dtype('int64'),
  'saves': dtype('int64'),
  'save_percentage': dtype('float64'),
  'punches': dtype('int64'),
  'clean_sheet': dtype('int64'),
  'goals_conceded': dtype('int64'),
  'penalty_saves': dtype('int64'),
  'distance_covered_km': dtype('float64'),
  'sprint_distance_km': dtype('float64'),
  'top_speed_kmh': dtype('float64'),
  'accelerations': dtype('int64'),
  'decelerations': dtype('int64'),
  'stamina_score': dtype('float64'),
  'player_rating': dtype('float64'),
  'performance_score': dtype('float64'),
  'offensive_contribution': dtype('float64'),
  'defensive_contribution': dtype('float64'),
  'possession_impact': dtype('float64'),
  'pressure_resistance': dtype('float64'),
  'creativity_score': dtype('float64'),
  'consistency_score': dtype('float64'),
  'clutch_performance_score': dtype('float64'),
  'total_goals_tournament': dtype('int64'),
  'total_assists_tournament': dtype('int64'),
  'total_minutes_tournament': dtype('int64'),
  'player_of_match_awards': dtype('int64'),
  'tournament_rating': dtype('float64')},
 'null_counts': {'player_id': 0,
  'player_name': 0,
  'age': 0,
  'nationality': 0,
  'team': 0,
  'jersey_number': 0,
  'position': 0,
  'height_cm': 0,
  'weight_kg': 0,
  'preferred_foot': 0,
  'club_name': 0,
  'market_value_eur': 0,
  'match_id': 0,
  'match_date': 0,
  'stadium': 0,
  'city': 0,
  'opponent_team': 0,
  'tournament_stage': 0,
  'match_result': 0,
  'goals_team': 0,
  'goals_opponent': 0,
  'minutes_played': 0,
  'goals': 0,
  'assists': 0,
  'shots': 0,
  'shots_on_target': 0,
  'expected_goals_xg': 0,
  'expected_assists_xa': 0,
  'key_passes': 0,
  'successful_passes': 0,
  'total_passes': 0,
  'pass_accuracy': 0,
  'dribbles_attempted': 0,
  'successful_dribbles': 0,
  'crosses': 0,
  'successful_crosses': 0,
  'tackles': 0,
  'interceptions': 0,
  'clearances': 0,
  'blocks': 0,
  'aerial_duels_won': 0,
  'aerial_duels_lost': 0,
  'recoveries': 0,
  'defensive_actions': 0,
  'fouls_committed': 0,
  'fouls_suffered': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'offsides': 0,
  'saves': 0,
  'save_percentage': 0,
  'punches': 0,
  'clean_sheet': 0,
  'goals_conceded': 0,
  'penalty_saves': 0,
  'distance_covered_km': 0,
  'sprint_distance_km': 0,
  'top_speed_kmh': 0,
  'accelerations': 0,
  'decelerations': 0,
  'stamina_score': 0,
  'player_rating': 0,
  'performance_score': 0,
  'offensive_contribution': 0,
  'defensive_contribution': 0,
  'possession_impact': 0,
  'pressure_resistance': 0,
  'creativity_score': 0,
  'consistency_score': 0,
  'clutch_performance_score': 0,
  'total_goals_tournament': 0,
  'total_assists_tournament': 0,
  'total_minutes_tournament': 0,
  'player_of_match_awards': 0,
  'tournament_rating': 0},
 'total_rows': 54600,
 'column_types': {'categorical': ['player_id',
   'player_name',
   'age',
   'nationality',
   'team',
   'jersey_number',
   'position',
   'height_cm',
   'weight_kg',
   'preferred_foot',
   'club_name',
   'market_value_eur',
   'stadium',
   'city',
   'opponent_team',
   'tournament_stage',
   'match_result',
   'goals_team',
   'goals_opponent',
   'minutes_played',
   'goals',
   'assists',
   'shots',
   'shots_on_target',
   'expected_goals_xg',
   'expected_assists_xa',
   'key_passes',
   'successful_passes',
   'total_passes',
   'pass_accuracy',
   'dribbles_attempted',
   'successful_dribbles',
   'crosses',
   'successful_crosses',
   'tackles',
   'interceptions',
   'clearances',
   'blocks',
   'aerial_duels_won',
   'aerial_duels_lost',
   'recoveries',
   'defensive_actions',
   'fouls_committed',
   'fouls_suffered',
   'yellow_cards',
   'red_cards',
   'offsides',
   'saves',
   'save_percentage',
   'punches',
   'clean_sheet',
   'goals_conceded',
   'penalty_saves',
   'distance_covered_km',
   'sprint_distance_km',
   'top_speed_kmh',
   'accelerations',
   'decelerations',
   'stamina_score',
   'player_rating',
   'performance_score',
   'offensive_contribution',
   'defensive_contribution',
   'possession_impact',
   'pressure_resistance',
   'creativity_score',
   'consistency_score',
   'clutch_performance_score',
   'total_goals_tournament',
   'total_assists_tournament',
   'total_minutes_tournament',
   'player_of_match_awards',
   'tournament_rating'],
  'numerical': [],
  'datetime': ['match_id', 'match_date'],
  'text': []}}

In [10]:
df.drop_duplicates()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [ ]:
# in progress ...